# Base URL for the ToscaLabs website.
#
# Used to generate absolute links for the site
base_url = "https://toscalabs.org"
# Website title
title = "ToscaLabs"
# Website description
description = "The ToscaLabs website"

# Theme used for the website
theme = "tosca-theme"

# Specify the default language of the website
default_language = "en"
# Specify whether or not to generate RSS/Atom feeds for the website
generate_feeds = true
# Specify whether or not to generate a sitemap for the website
generate_sitemap = true

[markdown]
# Render emojis
render_emoji = true

# Links
#
# External links are to be opened in a new tab. A `rel="noopener"` will always
# automatically be added for security reasons.
external_links_target_blank = true
# Set `rel="nofollow"` for all external links
external_links_no_follow = true
# Set `rel="noreferrer"` for all external links
external_links_no_referrer = true
# Set `rel="external"` for all external links
external_links_external = true

# Footnotes
#
# Footnotes are rendered in the GitHub-style
# [at the bottom, with back references]
bottom_footnotes = true

# Alerts
#
# Support for GitHub-style alerts
github_alerts = true

[markdown.highlighting]
# Missing highlight languages are treated as errors.
error_on_missing_language = true
# Use CSS classes.
style = "inline"
# Use dark theme to highlight code.
theme = "github-light"

# Section to configure specific settings for the Italian language
[languages.it]
# Generate RSS/Atom feeds for the Italian version of the website
generate_feeds = true
# Italian website title
title = "ToscaLabs"
# Italian website description
description = "Il sito di ToscaLabs"

# All custom theme variables must be placed here
[extra]
# ToscaLabs informative email
email = "info@toscalabs.org"

# Footer copyright text in different languages
copyright_map = { en = "All rights reserved.", it = "Tutti i diritti riservati." }

# GitHub link description in different languages
github_map = { en = "Visit ToscaLabs projects", it = "Guarda i progetti di ToscaLabs" }

# GitHub link
github_link = "https://github.com/ToscaLabs"

# Menu items in English
nav_items = [
    { name = "Home", prefix = "", url = "/" },
    { name = "Tosca", prefix = "",  url = "/tosca" },
    { name = "About", prefix = "",  url = "/about" },
    { name = "Blog", prefix = "",  url = "/blog" },
    { name = "Contact Us", prefix = "", url = "/#contacts" },
]

# Menu items in Italian
nav_items_it = [
    { name = "Home", prefix ="/it", url = "/" },
    { name = "Tosca", prefix = "/it", url = "/tosca" },
    { name = "Chi Siamo", prefix = "/it", url = "/chi-siamo" },
    { name = "Blog", prefix = "/it",  url = "/blog" },
    { name = "Contattaci", prefix = "/it", url = "/#contatti" },
]

# Taxonomies
taxonomies = [
  { name = "tags" }
]
